use estate_manager;

create table data_address (
	DistrictID int,
    Name varchar(20)
);

insert into data_address values (1, 'Tân Định');
insert into data_address values (1, 'Đa Kao');
insert into data_address values (1, 'Bến Nghé');
insert into data_address values (1, 'Bến Thành');
insert into data_address values (1, 'Nguyễn Thái Bình');
insert into data_address values (1, 'Phạm Ngũ Lão');
insert into data_address values (1, 'Cầu Ông Lãnh');
insert into data_address values (1, 'Cô Giang');
insert into data_address values (1, 'Nguyễn Cư Trinh');
insert into data_address values (1, 'Cầu Kho');

insert into data_address values (2, 'Thảo Điền');
insert into data_address values (2, 'An Phú');
insert into data_address values (2, ' Bình An');
insert into data_address values (2, 'Bình Trưng Đông');
insert into data_address values (2, 'Bình Trưng Tây');
insert into data_address values (2, 'Bình Khánh');
insert into data_address values (2, 'An Khánh');
insert into data_address values (2, 'Cát Lái');
insert into data_address values (2, 'Thạnh Mỹ Lợi');
insert into data_address values (2, 'An Lợi Đông');
insert into data_address values (2, 'Thủ Thiêm');

insert into data_address values (3, '1');
insert into data_address values (3, '2');
insert into data_address values (3, '3');
insert into data_address values (3, '4');
insert into data_address values (3, '5');
insert into data_address values (3, '6');
insert into data_address values (3, '7');
insert into data_address values (3, '8');
insert into data_address values (3, '9');
insert into data_address values (3, '10');
insert into data_address values (3, '11');
insert into data_address values (3, '12');
insert into data_address values (3, '13');
insert into data_address values (3, '14');

insert into data_address values (4, '1');
insert into data_address values (4, '2');
insert into data_address values (4, '3');
insert into data_address values (4, '4');
insert into data_address values (4, '5');
insert into data_address values (4, '6');
insert into data_address values (4, '8');
insert into data_address values (4, '9');
insert into data_address values (4, '10');
insert into data_address values (4, '12');
insert into data_address values (4, '13');
insert into data_address values (4, '14');
insert into data_address values (4, '15');
insert into data_address values (4, '16');
insert into data_address values (4, '18');

insert into data_address values (5, '1');
insert into data_address values (5, '2');
insert into data_address values (5, '3');
insert into data_address values (5, '4');
insert into data_address values (5, '5');
insert into data_address values (5, '6');
insert into data_address values (5, '7');
insert into data_address values (5, '8');
insert into data_address values (5, '9');
insert into data_address values (5, '10');
insert into data_address values (5, '11');
insert into data_address values (5, '12');
insert into data_address values (5, '13');
insert into data_address values (5, '14');
insert into data_address values (5, '15');

insert into data_address values (6, '1');
insert into data_address values (6, '2');
insert into data_address values (6, '3');
insert into data_address values (6, '4');
insert into data_address values (6, '5');
insert into data_address values (6, '6');
insert into data_address values (6, '7');
insert into data_address values (6, '8');
insert into data_address values (6, '9');
insert into data_address values (6, '10');
insert into data_address values (6, '11');
insert into data_address values (6, '12');
insert into data_address values (6, '13');
insert into data_address values (6, '14');

insert into data_address values (7, 'Tân Thuận Đông');
insert into data_address values (7, 'Tân Thuận Tây');
insert into data_address values (7, 'Tân Kiểng');
insert into data_address values (7, 'Tân Hưng');
insert into data_address values (7, 'Bình Thuận');
insert into data_address values (7, 'Tân Quy');
insert into data_address values (7, 'Phú Thuận');
insert into data_address values (7, 'Tân Phú');
insert into data_address values (7, 'Tân Phong');
insert into data_address values (7, 'Phú Mỹ');

insert into data_address values (8, '1');
insert into data_address values (8, '2');
insert into data_address values (8, '3');
insert into data_address values (8, '4');
insert into data_address values (8, '5');
insert into data_address values (8, '6');
insert into data_address values (8, '7');
insert into data_address values (8, '8');
insert into data_address values (8, '9');
insert into data_address values (8, '10');
insert into data_address values (8, '11');
insert into data_address values (8, '12');
insert into data_address values (8, '13');
insert into data_address values (8, '14');
insert into data_address values (8, '15');
insert into data_address values (8, '16');

insert into data_address values (9, 'Long Bình');
insert into data_address values (9, 'Long Thạnh Mỹ');
insert into data_address values (9, 'Tân Phú');
insert into data_address values (9, 'Hiệp Phú');
insert into data_address values (9, 'Tăng Nhơn Phú A');
insert into data_address values (9, 'Tăng Nhơn Phú B');
insert into data_address values (9, 'Phước Long B');
insert into data_address values (9, 'Phước Long A');
insert into data_address values (9, 'Trường Thạnh');
insert into data_address values (9, 'Long Phước');
insert into data_address values (9, 'Long Trường');
insert into data_address values (9, 'Phước Bình');
insert into data_address values (9, 'Phú Hữu');

insert into data_address values (10, '1');
insert into data_address values (10, '2');
insert into data_address values (10, '3');
insert into data_address values (10, '4');
insert into data_address values (10, '5');
insert into data_address values (10, '6');
insert into data_address values (10, '7');
insert into data_address values (10, '8');
insert into data_address values (10, '9');
insert into data_address values (10, '10');
insert into data_address values (10, '11');
insert into data_address values (10, '12');
insert into data_address values (10, '13');
insert into data_address values (10, '14');
insert into data_address values (10, '15');

insert into data_address values (11, '1');
insert into data_address values (11, '2');
insert into data_address values (11, '3');
insert into data_address values (11, '4');
insert into data_address values (11, '5');
insert into data_address values (11, '6');
insert into data_address values (11, '7');
insert into data_address values (11, '8');
insert into data_address values (11, '9');
insert into data_address values (11, '10');
insert into data_address values (11, '11');
insert into data_address values (11, '12');
insert into data_address values (11, '13');
insert into data_address values (11, '14');
insert into data_address values (11, '15');
insert into data_address values (11, '16');

insert into data_address values (12, 'Phường Thạnh Xuân');
insert into data_address values (12, 'Thạnh Lộc');
insert into data_address values (12, 'Hiệp Thành');
insert into data_address values (12, 'Thới An');
insert into data_address values (12, 'Tân Chánh Hiệp');
insert into data_address values (12, 'An Phú Đông');
insert into data_address values (12, 'Tân Thới Hiệp');
insert into data_address values (12, 'Trung Mỹ Tây');
insert into data_address values (12, 'Tân Hưng Thuận');
insert into data_address values (12, 'Đông Hưng Thuận');
insert into data_address values (12, 'Tân Thới Nhất');

insert into data_address values (13, 'Linh Xuân');
insert into data_address values (13, 'Bình Chiểu');
insert into data_address values (13, 'Linh Trung');
insert into data_address values (13, 'Tam Bình');
insert into data_address values (13, 'Tam Phú');
insert into data_address values (13, 'Hiệp Bình Phước');
insert into data_address values (13, 'Hiệp Bình Chánh');
insert into data_address values (13, 'Linh Chiểu');
insert into data_address values (13, 'Linh Tây');
insert into data_address values (13, 'Linh Đông');
insert into data_address values (13, 'Bình Thọ');
insert into data_address values (13, 'Trường Thọ');

insert into data_address values (14, '1');
insert into data_address values (14, '2');
insert into data_address values (14, '3');
insert into data_address values (14, '4');
insert into data_address values (14, '5');
insert into data_address values (14, '6');
insert into data_address values (14, '7');
insert into data_address values (14, '8');
insert into data_address values (14, '9');
insert into data_address values (14, '10');
insert into data_address values (14, '11');
insert into data_address values (14, '12');
insert into data_address values (14, '13');
insert into data_address values (14, '14');
insert into data_address values (14, '15');
insert into data_address values (14, '16');

insert into data_address values (15, '1');
insert into data_address values (15, '2');
insert into data_address values (15, '3');
insert into data_address values (15, '5');
insert into data_address values (15, '6');
insert into data_address values (15, '7');
insert into data_address values (15, '11');
insert into data_address values (15, '12');
insert into data_address values (15, '13');
insert into data_address values (15, '14');
insert into data_address values (15, '15');
insert into data_address values (15, '17');
insert into data_address values (15, '19');
insert into data_address values (15, '21');
insert into data_address values (15, '22');
insert into data_address values (15, '24');
insert into data_address values (15, '25');
insert into data_address values (15, '26');
insert into data_address values (15, '27');
insert into data_address values (15, '28');

insert into data_address values (16, '1');
insert into data_address values (16, '2');
insert into data_address values (16, '3');
insert into data_address values (16, '4');
insert into data_address values (16, '5');
insert into data_address values (16, '6');
insert into data_address values (16, '7');
insert into data_address values (16, '8');
insert into data_address values (16, '9');
insert into data_address values (16, '10');
insert into data_address values (16, '11');
insert into data_address values (16, '12');
insert into data_address values (16, '13');
insert into data_address values (16, '14');
insert into data_address values (16, '15');

insert into data_address values (17, 'Tân Sơn Nhì');
insert into data_address values (17, 'Tây Thạnh');
insert into data_address values (17, 'Sơn Kỳ');
insert into data_address values (17, 'Tân Quý');
insert into data_address values (17, 'Tân Thành');
insert into data_address values (17, 'Phú Thọ Hòa');
insert into data_address values (17, 'Phú Thạnh');
insert into data_address values (17, 'Phú Trung');
insert into data_address values (17, 'Hòa Thạnh');
insert into data_address values (17, 'Hiệp Tân');
insert into data_address values (17, 'Tân Thới Hòa');

insert into data_address values (18, '1');
insert into data_address values (18, '2');
insert into data_address values (18, '3');
insert into data_address values (18, '4');
insert into data_address values (18, '5');
insert into data_address values (18, '6');
insert into data_address values (18, '7');
insert into data_address values (18, '8');
insert into data_address values (18, '9');
insert into data_address values (18, '10');
insert into data_address values (18, '11');
insert into data_address values (18, '12');
insert into data_address values (18, '13');
insert into data_address values (18, '14');
insert into data_address values (18, '15');

insert into data_address values (19, 'Bình Hưng Hòa');
insert into data_address values (19, 'Bình Hưng Hoà A');
insert into data_address values (19, 'Bình Hưng Hoà B');
insert into data_address values (19, 'Bình Trị Đông');
insert into data_address values (19, 'Bình Trị Đông A');
insert into data_address values (19, 'Bình Trị Đông B');
insert into data_address values (19, 'Tân Tạo');
insert into data_address values (19, 'Tân Tạo A');
insert into data_address values (19, 'An Lạc');
insert into data_address values (19, 'An Lạc A');

insert into data_address values (20, 'Thị trấn Củ Chi');
insert into data_address values (20, 'Phú Mỹ Hưng');
insert into data_address values (20, 'An Phú');
insert into data_address values (20, 'Trung Lập Thượng');
insert into data_address values (20, 'An Nhơn Tây');
insert into data_address values (20, 'Nhuận Đức');
insert into data_address values (20, 'Phạm Văn Cội');
insert into data_address values (20, 'Phú Hòa Đông');
insert into data_address values (20, 'Trung Lập Hạ');
insert into data_address values (20, 'Trung An');
insert into data_address values (20, 'Phước Thạnh');
insert into data_address values (20, 'Phước Hiệp');
insert into data_address values (20, 'Tân An Hội');
insert into data_address values (20, 'Phước Vĩnh An');
insert into data_address values (20, 'Thái Mỹ');
insert into data_address values (20, 'Tân Thạnh Tây');
insert into data_address values (20, 'Hòa Phú');
insert into data_address values (20, 'Tân Thạnh Đông');
insert into data_address values (20, 'Bình Mỹ');
insert into data_address values (20, 'Tân Phú Trung');
insert into data_address values (20, 'Tân Thông Hội');

insert into data_address values (21, 'Thị trấn Hóc Môn');
Insert into data_address values (21, 'Tân Hiệp');
Insert into data_address values (21, 'Nhị Bình');
Insert into data_address values (21, 'Đông Thạnh');
Insert into data_address values (21, 'Tân Thới Nhì');
Insert into data_address values (21, 'Thới Tam Thôn');
Insert into data_address values (21, 'Xuân Thới Sơn');
Insert into data_address values (21, 'Tân Xuân');
Insert into data_address values (21, 'Xuân Thới Đông');
Insert into data_address values (21, 'Trung Chánh');
Insert into data_address values (21, 'Xuân Thới Thượng');
Insert into data_address values (21, 'Bà Điểm');

Insert into data_address values (22, 'Thị trấn Tân Túc');
Insert into data_address values (22, 'Phạm Văn Hai');
Insert into data_address values (22, 'Vĩnh Lộc A');
Insert into data_address values (22, 'Vĩnh Lộc B');
Insert into data_address values (22, 'Bình Lợi');
Insert into data_address values (22, 'Lê Minh Xuân');
Insert into data_address values (22, 'Tân Nhựt');
Insert into data_address values (22, 'Tân Kiên');
Insert into data_address values (22, 'Bình Hưng');
Insert into data_address values (22, 'Phong Phú');
Insert into data_address values (22, 'An Phú Tây');
Insert into data_address values (22, 'Hưng Long');
Insert into data_address values (22, 'Đa Phước');
Insert into data_address values (22, 'Tân Quý Tây');
Insert into data_address values (22, 'Bình Chánh');
Insert into data_address values (22, 'Quy Đức');

Insert into data_address values (23, 'Thị trấn Nhà Bè');
Insert into data_address values (23, 'Phước Kiển');
Insert into data_address values (23, 'Phước Lộc');
Insert into data_address values (23, 'Nhơn Đức');
Insert into data_address values (23, 'Phú Xuân');
Insert into data_address values (23, 'Long Thới');
Insert into data_address values (23, 'Hiệp Phước');

Insert into data_address values (24, 'Thị trấn Cần Thạnh');
Insert into data_address values (24, 'Bình Khánh');
Insert into data_address values (24, 'Tam Thôn Hiệp');
Insert into data_address values (24, 'An Thới Đông');
Insert into data_address values (24, 'Thạnh An');
Insert into data_address values (24, 'Long Hòa');
Insert into data_address values (24, 'Lý Nhơn');




